### ISSUE TITLE
Should setup travis to automatically build all branches and PRs.

### ISSUE THREAD

**Issue by skyem123** [Nightfall/SRails#3]
This is so that @Achati can have it so that all commits must pass a check before they are merged into master...

**Comment by NikkyAI** [comment]
https://github.com/blog/2051-protected-branches-and-required-status-checks
how much of that can we use?

**Comment by skyem123** [comment]
Well, we need travis to automatically build branches, and if it builds, we can merge with master.
The setting needs travis to do the status checks to be of any value.

**Comment by skyem123** [comment]
Right, this is done!
